apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-payment-api-config
  namespace: payment-service
data:
  NODE_ENV: "production"
  SERVICE_PORT: "3003"
  # MongoDB configuration will be set via environment variables
  # MONGODB_URI will be provided via Secret 