apiVersion: v1
kind: Secret
metadata:
  name: tech-payment-api-secret
  namespace: payments-service
type: Opaque
data:
  # MONGODB_URI will be set by GitHub Actions workflow
  # This is just a template - the actual secret is created dynamically 