name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    # - name: Run linting
    #   run: npm run lint
      
    # - name: Run tests
    #   run: npm test
      
    - name: Build application
      run: npm run build

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        
    - name: Update kube config
      run: aws eks update-kubeconfig --region us-east-1 --name tech_challenge_cluster
      
    - name: Get external service URLs
      id: service-urls
      run: |
        # Get MOCK_PAYMENT_SERVICE_URL from LoadBalancer
        MOCK_PAYMENT_EXTERNAL_IP=$(kubectl get svc pagamento-mock-service-loadbalancer -n pagamento-mock-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "")
        
        if [ -n "$MOCK_PAYMENT_EXTERNAL_IP" ]; then
          MOCK_PAYMENT_SERVICE_URL="http://${MOCK_PAYMENT_EXTERNAL_IP}:4000"
          echo "mock_payment_service_url=$MOCK_PAYMENT_SERVICE_URL" >> $GITHUB_OUTPUT
          echo "✅ Mock Payment Service URL retrieved: $MOCK_PAYMENT_SERVICE_URL"
        else
          MOCK_PAYMENT_SERVICE_URL="http://pagamento-mock-service-loadbalancer.pagamento-mock-service.svc.cluster.local:4000"
          echo "mock_payment_service_url=$MOCK_PAYMENT_SERVICE_URL" >> $GITHUB_OUTPUT
          echo "⚠️  Using fallback Mock Payment Service URL: $MOCK_PAYMENT_SERVICE_URL"
        fi
        
        # Get ORDER_API_URL from LoadBalancer
        ORDER_EXTERNAL_IP=$(kubectl get svc orders-service-loadbalancer -n orders-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "")
        
        if [ -n "$ORDER_EXTERNAL_IP" ]; then
          ORDER_API_URL="http://${ORDER_EXTERNAL_IP}:3000"
          echo "order_api_url=$ORDER_API_URL" >> $GITHUB_OUTPUT
          echo "✅ Order API URL retrieved: $ORDER_API_URL"
        else
          ORDER_API_URL="http://orders-service-loadbalancer.orders-service.svc.cluster.local:3000"
          echo "order_api_url=$ORDER_API_URL" >> $GITHUB_OUTPUT
          echo "⚠️  Using fallback Order API URL: $ORDER_API_URL"
        fi
        
    - name: Deploy to Kubernetes
      run: |
        # Generate Kubernetes manifests
        envsubst < k8s/deployment.yaml.template > k8s/deployment.yaml
        envsubst < k8s/service.yaml.template > k8s/service.yaml
        
        # Apply manifests
        kubectl apply -f k8s/namespace.yaml
        
        # Create secret with MongoDB connection string and external service URLs
        kubectl create secret generic tech-payment-api-secret \
          --from-literal=MONGODB_URI="${{ secrets.MONGODB_URI }}" \
          --from-literal=MOCK_PAYMENT_SERVICE_URL="${{ steps.service-urls.outputs.mock_payment_service_url }}" \
          --from-literal=ORDER_API_URL="${{ steps.service-urls.outputs.order_api_url }}" \
          --namespace=payments-service \
          --dry-run=client -o yaml | kubectl apply -f -
        
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/hpa.yaml
        
        # Wait for deployment to be ready
        kubectl rollout status deployment/tech-payment-api -n payments-service --timeout=300s
      env:
        DOCKER_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        SERVICE_NAME: tech-payment-api
        SERVICE_PORT: "3003"
        NAMESPACE: payments-service
        DOMAIN_NAME: tech-challenge.local 