name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Kubernetes namespace'
        required: true
        default: 'payment-service'
        type: string
      deployment:
        description: 'Deployment name'
        required: true
        default: 'tech-payment-api'
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        
    - name: Update kube config
      run: aws eks update-kubeconfig --region us-east-1 --name tech_challenge_cluster
      
    - name: Check deployment history
      run: |
        echo "Checking deployment history for ${{ inputs.deployment }} in namespace ${{ inputs.namespace }}"
        kubectl rollout history deployment/${{ inputs.deployment }} -n ${{ inputs.namespace }}
        
    - name: Rollback deployment
      run: |
        echo "Rolling back deployment ${{ inputs.deployment }} in namespace ${{ inputs.namespace }}"
        
        # Rollback to the previous revision
        kubectl rollout undo deployment/${{ inputs.deployment }} -n ${{ inputs.namespace }}
        
        # Wait for the rollback to complete
        kubectl rollout status deployment/${{ inputs.deployment }} -n ${{ inputs.namespace }} --timeout=300s
        
        # Verify the rollback
        echo "Verifying rollback..."
        kubectl get pods -n ${{ inputs.namespace }}
        
    - name: Rollback summary
      run: |
        echo "## 🔄 Rollback Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Rollback Details:**" >> $GITHUB_STEP_SUMMARY
        echo "- **Deployment:** ${{ inputs.deployment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Namespace:** ${{ inputs.namespace }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Action:** Rolled back to previous revision" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Current Status:**" >> $GITHUB_STEP_SUMMARY
        echo "```bash" >> $GITHUB_STEP_SUMMARY
        kubectl get pods -n ${{ inputs.namespace }} >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY 